---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "ubuntu"
    tag: "latest"

inputs:
- name: my-application
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: my-application/ci/tasks/app-manifest-prep
