---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "maven"
    tag: "latest"

inputs:
- name: my-application

outputs:
- name: app-manifest-output

run:
  path: my-application/ci/tasks/run-unit-test
