---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: my-application
- name: current-app-info

run:
  path: my-application/ci/tasks/update-routes
