groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - contract-tests
  - promote-new-version

resources:
- name: my-application
  type: git
  source:
    branch: master
    uri: https://github.com/sbalashevich/sample
- name: my-application-contract-tests
  type: git
  source:
    branch: master
    uri: https://github.com/sbalashevich/sample-contracts
- name: CF
  type: cf
  source:
    api: {{cf-api}}
    organization: {{cf-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{cf-space}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: my-application
    trigger: true
  - task: run-unit-tests
    file: my-application/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: my-application
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: my-application/ci/tasks/current-app-get-info.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-organization}}
      CF_USER: {{deploy-username}}
      CF_PWD: {{deploy-password}}
      CF_SPACE: {{cf-space}}
  - task: prepare-app-manifest
    file: my-application/ci/tasks/app-manifest-prep.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
  - put: CF
    params:
      manifest: app-manifest-output/manifest.yml
      path: my-application/target/sample-0.0.1-SNAPSHOT.jar

- name: contract-tests
  serial: true
  public: true
  plan:
  - get: my-application-contract-tests
  - get: my-application
    trigger: true
    passed:
      - deploy-app
  - task: get-current-app-color
    file: my-application/ci/tasks/current-app-get-info.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-organization}}
      CF_USER: {{deploy-username}}
      CF_PWD: {{deploy-password}}
      CF_SPACE: {{cf-space}}
  - task: run-contract-tests
    file: my-application/ci/tasks/contract-tests.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_APP_DOMAIN: {{cf-app-domain}}

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: my-application
    trigger: true
    passed:
      - contract-tests
  - task: get-current-app-color
    file: my-application/ci/tasks/current-app-get-info.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-organization}}
      CF_USER: {{deploy-username}}
      CF_PWD: {{deploy-password}}
      CF_SPACE: {{cf-space}}
  - task: switch-app-routes
    file: my-application/ci/tasks/update-routes.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_APP_DOMAIN: {{cf-app-domain}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-organization}}
      CF_USER: {{deploy-username}}
      CF_PWD: {{deploy-password}}
      CF_SPACE: {{cf-space}}
